scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']